import { Materials } from './materials';

export const MATERIALS: Materials[] = [
{ id: 11,
  name: 'Harry Potter og de vises sten',
  resume: 'Harry Potter og De Vises Sten er den første bog i serien om drengen Harry Potter, der på sin 11-års fødselsdag finder ud af, at han er en troldmand',
  status: true,
  forfatter: 'J.K. Rowling',
  imagePath: 'http://t0.gstatic.com/images?q=tbn:ANd9GcSKL5_5TfA5_e9SJSXKKyhQmLA7vD-kGqvsFheQaPo9PckwNVuV' },
{ id: 12,
  name: 'Harry Potter og Hemmelighedernes Kammer',
  resume: 'Harry Potter og Hemmelighedernes Kammer er den anden roman i serien om Harry Potter, der er skrevet af J. K. Rowling. Historien følger Harrys andet år på Hogwarts, hvor en række beskeder dukker op på skolens vægge.',
  status: true,
  forfatter: 'J.K. Rowling',
  imagePath: 'http://t0.gstatic.com/images?q=tbn:ANd9GcQopG-5dUtkLnw2foe3296353NLF3L0tBIDwzYENV1qQTKIx9BB' },
{ id: 13,
  name: 'Harry Potter og fangen fra Azkaban',
  resume: 'Harry Potter og fangen fra Azkaban er den tredje roman i Harry Potter-serien skrevet af J.K. Rowling. Bogen er filmatiseret under samme titel.',
  status: false,
  forfatter: 'J.K. Rowling',
  imagePath: 'http://t1.gstatic.com/images?q=tbn:ANd9GcQqIQ_hn_oj3AB_4Zk1mXicR7scAZEua33oNHlBbpzDN2l_u4rK' },
{ id: 14,
  name: 'Kampen om tronen',
  resume: 'Kampen om tronen er den første bog i A Song of Ice and Fire, en serie af fantasyromaner af den amerikanske forfatter George R. R. Martin. Den blev udgivet første gang den 6. august 1996 på engelsk.',
  status: false,
  forfatter: 'George R.R. Martin',
  imagePath: 'http://t2.gstatic.com/images?q=tbn:ANd9GcS4Oe69KTt1atcjURwMRtjq5H11u04xJcgfLY6GapC4sMEmepzL' },
{ id: 15,
  name: 'Kongernes kamp',
  resume: '"Kongernes kamp" er andet bind af George R.R. Martins storslåede romancyklus, som indledtes med "Kampen om tronen".',
  status: false,
  forfatter: 'George R.R. Martin',
  imagePath: 'http://t1.gstatic.com/images?q=tbn:ANd9GcQKW0WOSttdX6ViTG0GfNrOUQaFWlH2_Zr74Tf0UILrQXqAlGrU' },
{ id: 16,
  name: 'En storm af sværd',
  resume: 'En sang om Is og Ild/Game of Thrones, bind tre. Vesterøerne er nu delt mellem flere konger, og de forskellige huse kæmper om magten og overlevelse. Alliancer bliver indgået og brudt. En blodig krig raser i riget – og vinteren bliver barskere.',
  status: false,
  forfatter: 'George R.R. Martin',
  imagePath: 'http://t2.gstatic.com/images?q=tbn:ANd9GcS8h-Y3fcgn0YeNdq25EdSj0O8d32mMFs3_rzFPf2UnAR9VC5L3' },

];
